let allMessages = "";
let currentMessage;
let wipe = false;
let myInterval = 11; // 200

const messages = [
    "\"casey is always okay\" :D",
    "ssh casey@24.130.146.148",
    "yay, caseys must be very smart",
    "that's super cool though, I wouldn't be confused if I saw that as a non-casey thing",
    "nah, it was meant for a casey without context",
    "anything quite as unfortunate happened in casey life recently?",
    "I'll take notes on the different ways to not answer casey",
    "caseys are pretty competent too really",
    "WAIT CASEY OUR CLASSES ARE ACTUALLY THE SAME",
    "ohwait - there are casey classes tomorrow!",
    "idk what kind of a school you're going to casey",
    "but both are just like casey is a v good art person",
    "Okay, when do Caseys tend to be free?",
    "also wait haven't Casey classes started - why am I not interrogating you about your classes rather than being lectured about my playlists?",
    "I think it'd be a given - casey took lotsa spanish",
    "alright, just let me know at some point what times are good for Caseys",
    "just like your stuff is getting to the level that it's a bit strange to imagine Caseys making it - I expect that to be like a video game trailer/cinematic or something",
    "I should at some point find a time to talk to a Casey - since this is my long weekend and I am therefore slightly less dead than normal",
    "and I guess just to confirm - casey is still casey?",
    "did the casey do gud?",
    "Got egg bagels like a Casey",
    "wowo - or maybe I should just be saying casey has very impressive 3D art as usual at this point but",
    "yeah are you sure you haven't found yourself with some sort of right wing libertarian crowd casey?",
    "but I guess that means that casey is a straight who can provide the grandkiddos so as not to have sad parental units?",
    "this sounds so problematic casey",
    "what makes casey tired today?",
    "how are caseys?",
    "but gbye casey",
    "well thank you for life updates casey, I appreciate!",
    "that sounds way more casey, glad you found ways to pull strings",
    "well I guess this maybe harms my casey provides the grandkiddos strategy but",
    "im going to be honest casey the fact you’re doing this at all baffles me",
    "I'll hold onto your water bottle and headphones. You can come by and get them back, or I'll bring them over whenever we next see each other. Goodnight, Casey.",
    "ah was driving home and i was like.. huh i wonder what caseys up to",
    "no worries dear casey hope u r doing fantastic",
    "bye casey",
    "Slay casey",
    "That's too funny I'm sorry casey",
    "When casey not at core mtg",
    "Thank you Casey I will contribute with my figma design skills that I totally have",
    "Damn she was like yeah Casey is doing the web dev so ull be working w him",
    "Casey would u like to get a meal someday",
    "Hey Casey!!",
    "hey casey, just curious, have you played any dating sim before lol",
    "hey casey, would you mind helping put up some posters for our conference :p",
    "hi casey",
    "hey casey, want to grab a meal some time in the next few days?",
    "casey did u want to be in a group for the final proj!",
    "casey would you want to join vr hacks with me?",
    "!!! did you do it with the controllers casey",
    "hey casey! do you know how to install the occulus app on macbook?",
    "Thank you Casey!",
    "Casey? Cuz everyone is sorta clearing out.",
    "Hey Casey! Spotify recommended this song randomly but it reminded me of the angel thing u posted on ur ig story",
    "casey I’m so so happy for you!!!!",
    "hey casey are you taking cs148 this quarter?",
    "hey hey casey, they shouted out your game from cs44n in the recording for cs348c just now lol",
    "dis a casey core bnu",
    "casey noir era",
    "casey is a good sowftawre enginer",
    "when the casey",
    "aaa casey im sowwy i panic and am sad and called u so much :((((",
    "i like casey",
    "sleepy casey",
    "how casey?",
    "tge casey cave",
    "im sorry casey i know im a lot to handle",
    "should i forgib casey",
    "casey u dont have to if u dont wanna",
    "squishy casey",
    "winter break and winter quarter is one continuous period of not seeing casey",
    "oh no why casey pensive",
    "how is casey?",
    "how casey today?",
    "how will i talk to casey then :(",
    "vtuber casey",
    "soon i will take ur place as casey",
    "casey like powder blue confirmed",
    "casey likes gray confirmed?",
    "wat the casey doin",
    "how goes casey",
    "With Casey?;v",
    "Casey hii",
    "okey byebye casey",
    "other days are just casey days",
    "to have some talkative casey days",
    "today is talkative casey day",
    "casey r u up",
    "when will casey health",
    "I'm sowwy Casey",
    "edgelord casey",
    "how casey ?",
    "how casey go",
    "I sowwy Casey ;-;",
    "I won't be able to hang out with Casey",
    "Casey disappear",
    "My problems have no solutions - casey",
    "Coffee and Casey are of similar value",
    "casey is always okay",
    "lets no argue casey im sorry ;-;",
    "are u doing the fancy casey compositing",
    "sorry casey",
    "Seeing Casey is fun",
    "how the casey",
    "Casey always happens",
    "Ever since I grew a nose Casey has not spoken to me",
    "i am mentally preparing for the casey",
    "Smol casey",
    "Haha Casey hav nose",
    "casey is up",
    "how is casey?",
    "Casey made it",
    "What da Casey doin",
    "Casey does not equal grief",
    "Does Casey like boys now",
    "floofy casey",
    "one floofy casey pls",
    "I don’t like this being tied to a job casey…",
    "I don’t think that’s true Casey",
    "Casey how are you doingggg",
    "hey casey! what are you up to?",
    "casey, how far did y’all get in the book?",
    "Is Casey going to be there?",
    "Hi Casey! How are you! What have you been thinking about recently?",
    "Hey casey, are you in town? I just moved back",
    "CASEYYYY how well do u know her",
    "ur so fucking smart casey",
    "No worries casey!! Really hope you feel better soon 🥺",
    "I really wanna see you casey!!",
    "Hru casey",
    "happy for you Casey",
    "Really enjoyed it casey ",
    "i was like casey doesn’t want to talk to me :( when in fact you’re taking your time between lengthy replies",
    "happy thanksgiving casey!! grateful for you 🫶",
    "happy holidays casey!! hope you’re doing well",
    "so sorry fro my extremely late response to this. thanks so much for inviting casey!!",
    "Casey you’re trolling me rn",
    "casey. you gotta do something special. are there bunnies in your area",
    "hey Casey! was wondering if you’re on campus these days :) would be cool to catch up over lunch or something before i move",
    "CASEY wait it’s fully 1:05 you’re too fun to talk to",
    "Stay fighting the propaganda casey I believe in you",
    "Hey Casey! Just wanted to say that I’m missing ya",
    "Casey I’m spiraling please tell me what you’re thinking of ",
    "Casey this is so important. Do not bring toothpaste I have too much of it ",
    "What Casey no you’re very clearly Napoleon",
    "Casey may I suggested. Salt lake city haunted houses ",
    "casey you meet the most San Francisco people ",
    "Casey I was very high. Tried a new blend and it hit different. I opened my computer to text my mom and you were the chat I had pulled up",
    "Hi Casey!! Just thought of you and wanted to say hello :D",
    "Casey I need you to ship me your boss ",
    "Casey noooooo",
    "This is at Casey’s place?",
    "Between two women???? Casey that’s crazy don’t get in there",
    "But casey even if she didn’t commit crime against jackets she was stinky (and was not going to pay rent??)",
    "Casey. Ya gotta get out there. Gotta get out to Golden Gate Park. Gotta hike. Mmmm",
    "Casey!!! It’s great to hear from you! ",
    "Casey I like to think that I understood that poverty was bad and it’s impossible to escape but it’s IMPOSSIBLE to escape.",
    "Thaaanks casey",
    "Caseyyy listen—I knew you cooked, but like you definitely cooked here",
    "Emergenc is a booster casey it takes your current health and doubles it",
    "I can pick you up casey!!",
    "Are there any places you had in mind to go to casey? Since you live there now?",
    "We’re excited to see you casey ;)",
    "THIS is what makes casey actually respond in the gc? Vanilla??",
    "Wait caseyyyy do u want to talk to her about it?",
    "Awww casey ",
    "Hey Casey! Its a pleasure to be introduced",
    "I look forward to like caseys latte art",
    "frrrr yes I miss looking at a console.log(“it’s me”) and knowing that casey wrote it LMAO ",
    "Casey: “I just didn’t like his (baccalaureate speaker’s) vibe”",
    "not your “summer” being 2 weeks casey 😭😭",
    "Casey approval is huge",
    "casey do you like Environment. The big one, with rivers and stuff",
    "you have so much time casey",
    "I’m so anti work casey",
    "We left casey with friends ",
    "Casey and i are out",
    "Pour one out for casey",
    "Casey! Are u coming?",
    "“It’s ok we love them anyway” - casey ",
    "Casey it’s cute, I can give it to you!!",
    "I don’t wanna be on a campus with no churro AND no casey",
    "Casey. I know this is hard to hear but your son helicoil sucks. He’s the worst and he has been for a long time.",
    "Im in fitting room area. Waiting for casey to try on something",
    "Sorry casey ",
    "I’m on pins and fuckn needles over here casey ",
    "Casey there’s no such thing as a social order ",
    "Casey can i join u in lathrop?",
    "Casey what do you think?",
    "casey do u want to get coffee from 10:30-11:30?",
    "hi casey 😸",
    "The effort it takes not to scream CASEY rn",
    "Casey where you at?",
    "O shit we see you casey go offfff",
    "Casey!! She told me you might be coming on the yacht but are unsure of what to wear",
    "“This data is likely skewed because my friend Casey tries to skew it” ",
    "Thanks Casey you’re a legend",
    "Casey is fucking the AI w a shock collar",
    "“There’s legitimate historical basis to my work” - casey ",
    "If I leave it on your desk would you let casey in?",
    "Yay! Sg casey, I’ll also lyk closer to 3 if that’s ok?",
    "Idk what she’s thinking but Casey if ur down I’m still down ",
    "casey! did u drop moving image?",
    "Casey and I are in disbelief😂",
    "when are you traveling on wednesday Casey?",
    "No worries casey soldier 🫡 ",
    "casey coded",
    "Are we waiting for casey?",
    "casey can you let us in?",
    "Casey should let yall in from the side door ",
    "casey that was such a good essay omg. the second person is so you",
    "yayy!!! thank you casey",
    "death casey. Death",
    "Casey this show was NOT a romcom",
    "I’m not Arab caseyyyyy",
    "casey noooooo!! can i bribe u w turkey stock",
    "Are you coming to table Casey",
    "Best of luck Caseyy, they would be absolutely lucky to have you",
    "Thanks for understanding Casey",
    "hate is a 2 way street casey",
    "ahahha im literally gonna end up murdered one day casey ",
    "It was a hyperbole casey ",
    "keep up casey",
    "but im not gonna go full casey mode at them",
    "casey made a friend im so proud",
    "she’s like “this casey is cool but not toxic enough”",
    "“it looks like casey has news” is gonna put me in the hospital",
    "casey it happened to me ",
    "These are sooooooooo good casey ",
    "rare valid casey moment",
    "that so sweet casey ",
    "casey it’s a little bit isoppa ",
    "bad casey",
    "casey im actually so infuriated at you for how you perceive and treat your parents smh",
    "HHAHAHAH I KNOW THAT CASEY",
    "hey casey my friend is getting on grindr ",
    "Yahoo was the glue holding America together casey. Yahoo was like a brother to me ",
    "wtf casey do it ",
    "ok cool so no more casey ",
    "what if she had a baby casey ",
    "The smile of casey ",
    "The casey smile",
    "Give them the casey smile ",
    "yayyy the only thing i need is casey approval",
    "Hi Casey, how was your break :)) I need advice",
    "but toxic casey usually got a point",
    "ah the classic toxic casey",
    "You want fireworks Casey??? A music box???? Stick to scope ",
    "casey are u on snapchat",
    "casey heterophobic smh",
    "casey have u ever seen a picture of her",
    "CASEY NO",
    "casey nooo",
    "caseyy why arent u more susceptible to peer pressure",
    "casey what do you think is an acceptable age range for me",
    "caseyyy how do i text someone",
    "Ill be 10 min late to class casey! Marg was delayed😭",
    "Thank you Casey 🥹",
    "We aren’t gonna make it casey ",
    "Oh then it’s so over Casey. If I can’t find it it’s frankly over",
    "casey what time are you leaving?",
    "Casey and I on our way ",
    "Casey I am so scared of your car please drive ",
    "Casey who is itttttttt",
    "Never ever did you say that Casey oh my god",
    "CASEY ARE U STILL AT TRESSIDER. LET ME GET U A DRINK",
    "I think quite possibly Casey ",
    "wholesome casey moment",
    "casey this girl is so not good for you",
    "casey you passed out. That in of itself is bad ",
    "Casey casually throwing Ursula le guin into the chat ",
    "Caseyyyyy I WANT TO LEARN HOW YOU DO THIS WOW",
    "Casey did you spend your whole afternoon on it😭",
    "Okie Casey I’m gonna try to sleep since it’s 1:30 here",
    "casey it’s only a few hours 😭",
    "casey it is unhealthy how much of this gibberish i speak with a stuffed rabbit",
    "Casey should I be concerned ",
    "Caseyyyy I’m in love with how creative people are ",
    "Casey on the way to “get a berry for a bunny” as we speak ",
    "Hey Casey, how’s it going! Was wondering if you wanted to get lunch sometime?",
    "It’s over casey. But when the night is darkest the sun begins to rise. We must rally",
    "Thanks for sending Casey ",
    "Source: Casey here",
    "yay you should do it!!! also I was literally just playing ghost train and Casey it is so good!!!!! (charlie scares me a little LOL)",
    "Now’s your chance casey",
    "I can’t do this casey ",
    "So Casey bestie ",
    "so Casey that sentence was NOT vibes ",
    "Awwww caseyyyyy",
    "I’m so worried Casey what ",
    "This was an emotional rollercoaster to go through Casey ",
    "casey i think my mom drove by me as i was walking down the street ",
    "casey only wormed people know that suffix",
    "casey we have a problem",
    "ok this pic is much less casey like",
    "walking a fine line there casey",
    "the notion of the humble boymoder is a mere facade casey",
    "casey these prof's lectures suck but his accent is so adorable i can power through them",
    "casey the first 10 seconds of this video has the thing u told me not to google",
    "caseyy ur my only source u have to be reliablee",
    "casey do u think i have high-quality blooms",
    "casey why would u say thatttt",
    "casey i’m looking at pictures of bunnies rn",
    "oh shit philosopher casey moment",
    "the casey parents relationship is so back",
    "sober casey has too much nuance",
    "the planning session is in 40 minutes casey",
    "casey what's the etiquette on when ur going on dates and things are going rly well",
    "wait casey",
    "non wormed friends for casey!",
    "casey old welcome nightvale episodes are so funny rn",
    "we scheduled our third date casey",
    "omg casey i’m like so excited to talk with shindler about overhauling crumple trees lectures",
    "\"o shit\" is such a caseyism",
    "casey if ur into this thats great",
    "yayy casey toxicity filter is so non-permeable",
    "casey it's a fast food burger, every part of it is mid",
    "casey nooo the counter was up to one whole day",
    "casey this isn't college admissions where the more trauma the better",
    "oh fuck casey she offered me a ride to the party",
    "casey if we ever hang out and go somewhere off campus and she offers a ride we're golden",
    "o shit casey on the workout grindset lets gooo",
    "casey we gotta spread this around so i get invited to have coke snorted off my balls",
    "casey do u think i would have the grindset to be a startup bro",
    "casey both my friend groups do every week",
    "i just googled if casey is cognate with queso",
    "like maybe the first casey was a cheese maker",
    "Casey, You up for a Go game tomorrow?",
    "casey why does ur websites click and drag ball thing have a north and south pole that u can’t drag over",
    "i don’t mean go back to old casey",
    "caseyy im so excited for the picnic",
    "hey Casey it was really nice spending time with you last week <3",
    "casey it’s so over",
    "casey the words are bad",
    "casey you’ve never been more back",
    "casey i think i win",
    "“even if casey is being a lil bitch about it”",
    "words of a fool casey",
    "caseyy i need nuggies for energy to get out of bed to make nuggies",
    "caseyy go do all those things",
    "caseyy what does this mean im not an adult",
    "caseyy idk how taxes work i need to call my dad",
    "casey i was speaking at like two words per second",
    "casey they blundered i think u just have to roll with it",
    "o shit casey it might be extra over for u if ur sick again by the time the reschedule date comes around",
    "casey it’s basically on the calendar",
    "caseyy don’t text ur ex",
    "also caseyyy my goose is so fucking cooked for finals",
    "casey why are u wasting ur time in this job search",
    "\"deranged\" is a caseyism huh",
    "casey is it worth a few hours of displeasure",
    "casey i beansed it",
    "casey he's not cute",
    "wtfff casey text",
    "casey i dont have edit access",
    "casey 2 of them put lockheed martin as an interest",
    "casey i don’t think i can survive this quarter",
    "casey this is not ambiguous",
    "casey noooo",
    "casey do u know about the \"mister bonelli\" guy",
    "casey my parents just called me and asked about my graduation",
    "18 year old casey better watch out",
    "caseyyy thats not a good sign",
    "smh shallow casey moment",
    "casey she texted me this afternoon asking if i wanted to go to some thing this evening",
    "things are looking so good in casey world",
    "casey what",
    "dang i thought this was a casey specialty",
    "casey if u throw away ur palhah over this",
    "“casey’s so cool we should exchange brain rot”",
    "casey sf is so actually good",
    "hi casey!",
    "casey this woman is not an older  woman she is an olddd woman",
    "o shittt based casey’s mom",
    "casey this so does not sound like a normal individual",
    "most days casey coffee consumption is 1 cup",
    "caseyy we can come over saturday night for nightvale watch party (and take the stupid monitor) are u down for then",
    "yea mark it casey only",
    "omg omg casye casey can we  pleasese by an emd f40",
    "as opposed to the several other ians out there casey",
    "casey we got another one",
    "casey were unbelievably back",
    "casey we gotta",
    "casey it’s over for u",
    "casey are they gonna pay rent",
    "wtf casey why did u say that",
    "caseyy a very weird happened last night",
    "casey wtf",
    "casey i dont want a fucking snake in the house",
    "casey wtf no wonder she’s not into u",
    "casey you've seen the results of her thinking very highly of herself",
    "using the casey navigational system the closest park to our house is:",
    "wtf casey",
    "casey i would genuinely pay so much to see this",
    "casey i swear to god",
    "casey everyone is just a cute girl who wants to meet cute girls",
    "casey did u fuck up my bumper",
    "casey ur literally already in the polycule",
    "casey get in there",
    "casey how much do u know about his planned living situation for next year",
    "casey noooo",
    "it was one of the most awkward moments of my life casey",
    "casey we gotta fucking secure this deal",
    "casey i can hear ur conversation",
    "caseyyyyyy taktak ippita",
    "casey this is an ai company",
    "casey have you seen barbie yet",
    "casey when does your break start?",
    "right casey I have uno questiono for you",
    "Uh casey can you help me with the math hw",
    "i'm just playing casey",
    "I'll kill you casey if you don't like it",
    "im scared casey",
    "Alright casey",
    "come on then casey",
    "thanks for hearin me out casey",
    "why casey aren't you a talkative one",
    "sorry I was talking to casey bot",
    "its very casey",
    "im pro-casey",
    "you're a treasure, casey",
    "casey only makes smoothies now",
    "ur a treasure casey",
    "I want a casey moment",
    "mind if I invite casey if they're free?",
    "ok casey can't come today but can tmrw",
    "idk what train times work best for where but we could pick casey up from mtn view or san antonio",
    "okay this looks good - logistics might be hard for casey?",
    "could be nice to not drag cevi and casey down this time lol",
    "gonna make dinner with casey but i’m thinking meat",
    "i gangstalked casey and interrupted her family dinner ^_^",
    "casey i have plenty of social interactions",
    "hey casey guess who just binged all of what happens next",
    "casey adn I can be trusted to have healthy and realistic opinions and emoitons surrounding the \"blog\"",
    "casey could tell me to eat cement and i would do it",
    "wasnt casey trolling",
    "casey I think you hurt his feelings",
    "so as i do my explanation, i’ll be like “and the final step is to interpolate these four value, which casey will explain”",
    "casey how much is the garage rent",
    "wait casey this is fucking perfect",
    "casey you're so back",
    "omg good luck casey",
    "idk if it will work for casey",
    "how long did you live with a cat last time you did it casey",
    "im down if casey is",
    "casey deserves to be hit for that message!",
    "i don't want to use my brain casey",
    "oh casey i know what urs should be",
    "casey confirmed not truscum",
    "casey you aren't hyperplastic are you",
    "casey this doesn't help our understanding any",
    "yo casey, this doesnt add up",
    "casey you sack get in here",
    "smallsmalllsmalll small casey",
    "ahh casey help me pls",
    "casey u r stupid",
    "wait nvrmind casey just dind't do anything",
    "how would you govern the casey micronation",
    "you and i will make casey's dating profile",
    "Casey coming in to brighten this ugly ass town",
    "Casey. Listen when I tell you that it can just be shots of your hair",
    'ok casey you must send your datums',
    "Bruh casey stop texting lets just go somewhere",
    "hehe yeah i was like ... lemme ask Casey",
    "you got us addicted casey",
    "omg hi casey",
    "pluto is a no simp zone casey",
    "Caseyy you're back from Seattle!!",
    "Oh god oh no there went Casey",
    "Casey you look like a 2000s Disney channel star in their flop era",
    "I can go w Casey for cake",
    "Casey and I are going to make cauliflower and cheese and play go",
    "hey casey this seems mad fucking sus",
    "It's a pact Casey either we're both there or neither of us is",
    "Hey casey hope you're feeling ok! Are your symptoms bad?",
    "casey i miss you",
    "Casey don't quit the convo now",
    "Honestly casey I don't know",
    "I fucked up Casey",
    "not me sending this to casey",
    "Casey cmon now smh",
    "All Casey's fault",
    "Casey darling but of course",
    "hi casey! are you free for a quick call?",
    "casey it's been two days 😭😭",
    "Casey how is this possible",
    "Hey Casey, just a question what is the difference between build and and build and run?",
    "Casey I don't know how to tell you this but your experiences are not universal",
    "does that work for you casey :o",
    "what happened to casey ally to all",
    "me and casey are chilling on the roof",
    "It has the casey approval",
    "NO IT DOESN't CASEY",
    "Its over casey",
    "Gn casey hope you made it back safely",
    "I thought casey was liberated",
    "CASEY you are living large",
    "hey casey! we have our meeting rn",
    "Oh Casey of course",
    "ITS SO CUTE🥹🥹 i love this casey",
    "omg casey lives in one of the furthest row houses",
    "And the Casey corroboration??? This case is closed",
    "Casey she's SO FUCKING CUTEEEEE",
    "NOOOO casey dont give up",
    "\"Listen. Casey. This character needs less gender.\"",
    "casey can't wither",
    "hey casey! i forgot to log out of outlook on ur laptop 😭",
    "Oh my god Casey I nearly just died",
    "CASEY! i have a unity related question but it's not for our project! but!",
    "casey boy how's it going",
    "Diplomatic Casey",
    "Casey do you wanna meet at tres?",
    "Also casey is full of shit",
    "Also casey side note. i really appreciate you. get home safeeeee",
    "casey is that ok?",
    "GOT IT THANKS CASEY",
    "Casey help, how to quit discord",
    "Casey I just took a post clinic nap",
    "I'm so excited for it casey",
    "Casey ur photography is so cool!!",
    "Lmaoooo casey",
    "Casey is this just you getting the baby fever??",
    "changing Casey's contact name once again",
    "Nooo but vanilla extract is so good casey why is this a bad thing",
    "THATS SO BAD CASEY WHATTT",
    "hey casey when do you wanna leave today",
    "Apologies no one likes eggs except Casey",
    "Awww I'm sorry Casey",
    "Casey this was the cutest thing ever",
    "Oh my gosh Casey!!!!!",
    "Casey help me do you have social tact",
    "jiayou casey!",
    "casey become an english major 🥺",
    "hi casey :3",
    "nooo casey's braincells",
    "nooo casey's brain",
    "😭 ive weirded out casey",
    "casey ur not allowed to be sad or lazy",
    "oh no i scared casey with my mathematical competency 😔",
    "😭 casey has left the nest",
    "hi casey 👋",
    "casey do i trust you",
    "okay then casey :3",
    "sometimes I can't read the things casey texts in caseys voice for the life of me, and I feel like this is one of those phrases",
    "see casey, this is why i 👉 go to therapy",
    "wait I didn't know casey was an artist",
    "casey what's your name on spotify? I want to cyberstalk you",
    "i feel like it must be a site of powerful casey autism",
    "i’ve been daydreaming about saying “casey. please dispense a cigarette”",
    "it’s been a while since i got persnickety casey",
    "i’m gonna brush my teeth and sleep soon but i’ll be around if you wanna engage in some of your characteristic casey fast 😤 long 😤 texting",
    "i can try talking to her like i would talk to casey",
    "the little model of casey in my head was smiling as i wrote hehe",
    "input for the casey brain",
    "i will learn the casey ways",
    "the going-outdoors casey",
    "casey, a slave to the general vibe",
    "it’s so cute to be like “explain the tech term casey”",
    "spinning up my entire compute cluster to update my casey priors",
    "i just crave casey content",
    "going on what the kids call a casey stroll",
    "casey \"would be unhappy odysseus\" manning",
    "what’s the casey favorability on reading together for like 15 minutes before i sleep",
    "they call me casey the way i mmm",
    "frequently i start to make a noise and i don’t know what noise i intend to make and it’s casey noise",
    "i have this thesis that we are converging back to normal casey snippiness",
    "refrained from saying “u haven’t contemplated my face as much as casey probably”",
    "would u like to go on a casey stroll sometime today",
    "do you want me to make casey’s special low sodium green curry alongside normal curry",
    "i imagine painkillers casey is charming",
    "the casey bluntness",
    "is it casey alone before bed time",
    "return of the casey stroll",
    "the casey lol is like a dagger in my heart always",
    "i haven’t allowed myself to linger much on possible casey names",
    "like if we got vtuber stuff to a point where i could have a little animated speaking casey llm guy",
    "there’s this certain kind of casey inflection idk",
    "and it seems like casey is important to us and it would be good to focus on her and stabilize that for everyone involved",
    "i’m casey-moding in regard to this",
    "quite a casey stroll :)",
    "such a casey face",
    "begging, pleading for casey UX input",
    "it makes me sad how few casey photos",
    "total casey victory",
    "casey is saying Soon",
    "casey sick is a scourge",
    "i'm so caseypilled",
    "i’m so excited for casey underlings era",
    "total casey linguistic victory",
    "marginal improvements in casey wellness move the needle",
    "how is the casey this morn",
    "what’s the casey lore on seeing this movie",
    "in the long run casey and me are totally vindicated and also what ????",
    "i would have had to bully you so hard to get cute casey switzerland pics",
    "i will once again get to walk the casey",
    "believe it or not, casey-kun, i saw episode 2 and 3 in theaters",
    "casey this is so good",
    "the myth of consensual casey",
    "the thing about casey dissociation is that it’s buddha coded",
    "casey classic",
    "industry standard benchmark: digital twin of casey rating agents cringe and not cringe",
    "total casey victory omg",
    "was this a “casey computation situation”",
    "“casey is largely indifferent to the interesting social dynamic 😌”",
    "but i guess i was like mm this is a consistent revealed casey preference",
    "this is my casey analysis what do you think",
    "i think a lot of what i would find very fascinating in seeing your style develop would be what is a more conventional casey statement piece",
    "i request one (1) casey reflection or anecdote",
    "a fascinating glimpse into the casey mind",
    "casey-type activity",
    "salmon by casey (tm)",
    "walking down the street and a crowd of people starts chanting “casey”",
    "no so casey",
    "casey is lib, codes, bantz",
    "thank you casey",
    "casey if you form a tulpa I SWEAR TO GOD",
    "casey is a coward for withdrawing",
    "casey I can’t stop tearing at parts of my flesh",
    "wait casey what the fuck I just remembered we also still have to do the other problems",
    "casey speak truths to me",
    "casey that is such a bad dynamic, yeah. holy shit",
    "casey I hope youre doing alright",
    "casey i just watched myself fail a billion hard leetcodes u don’t wanna trust me with ur career",
    "this is the ant-casey",
    "I may disagree, but casey is able to do critical thinking",
    "oh casey and i might also go to banya in early evening (say 5-8?) for our new years mikveh",
    "am gonna pick up casey and actually have a bunch of extra time, anyone else need a ride lol",
    "cant believe casey has real website before i do",
    "website for casey????",
    "i disastered casey",
    "what if my domain was casey.business",
    "casey.watches.you",
    "you are casey :)",
    "send the Casey Collection",
    "casey i dont have any pants",
    "gatekeeping caseyness",
    "new behavior: chasing casey",
    "it feels like a compelling slice of casey life",
    "And like I’m in the “huge Casey believers club, dependent on artistic and career decisions over the next ten years, for which there is great tolerance/open space”",
    "I'm a very romantic person Casey",
    "I believe in the Casey Charm /srs",
    "but casey charm is real ❤️",
    "ok check it: casey.you",
    "\"casey business\" was determined to be slightly too silly.",
    "i’m just offended by the level of casey non-flourishing entailed",
    "i would really kill for casey girlfriends prose",
    "saw someone in old casey uniform just now",
    "strategic realignments in casey’s favor"
];


function chooseMessage() {
    currentMessage = messages[Math.floor(Math.random() * messages.length)].split(" ");
    let mayaIndex;
    let originalMaya;
    for (let i = 0; i < currentMessage.length; i++) {
        if (currentMessage[i].toLowerCase().includes("casey")) {
            mayaIndex = i;
            originalMaya = currentMessage[i];
        }
    }

    let preMaya = currentMessage.slice(0, mayaIndex);
    let preMayaNumCharacters = preMaya.join(" ").length;
    let postMaya = currentMessage.slice(mayaIndex + 1, currentMessage.length);
    let postMayaNumCharacters = postMaya.join(" ").length;

    let message = {
        "preMaya": preMaya,
        "preMayaNumCharacters": preMayaNumCharacters,
        "postMaya": postMaya,
        "postMayaNumCharacters": postMayaNumCharacters,
        "originalMaya": originalMaya
    }
    return message;

}

let textSpans = [];

function createNewMessage() {
    let newMessage = chooseMessage();
    while (newMessage.preMayaNumCharacters >= 20 && newMessage.postMayaNumCharacters >= 30) {
        newMessage = chooseMessage();
    }

    const newDiv = document.createElement("div");
    newDiv.classList.add("current-message");

    if (newMessage.preMayaNumCharacters > newMessage.postMayaNumCharacters) {
        // Left is longer
        newDiv.style.alignItems = "flex-end";
    } else {
        newDiv.style.alignItems = "flex-start";
    }

    // LEFT
    const leftSpan = document.createElement("span");
    leftSpan.classList.add("flex-item");
    leftSpan.classList.add("left");
    leftSpan.innerText = newMessage.preMaya.join(" ");
    newDiv.appendChild(leftSpan);
    leftSpan.style.transform = "translateY(0px)";
    leftSpan.title = leftSpan.innerText;
    textSpans.push(leftSpan);

    // CENTER
    const centerSpan = document.createElement("span");
    centerSpan.classList.add("flex-item");
    centerSpan.classList.add("center");
    centerSpan.innerText = newMessage.originalMaya;
    newDiv.appendChild(centerSpan);
    const randomDuration = Math.floor(Math.random() * 9) + 2;
    centerSpan.style.animation = `fadeIn ${randomDuration}s infinite`;
    centerSpan.title = centerSpan.innerText;
    textSpans.push(centerSpan);
    // RIGHT
    const rightSpan = document.createElement("span");
    rightSpan.classList.add("flex-item");
    rightSpan.classList.add("right");
    rightSpan.innerText = newMessage.postMaya.join(" ");
    newDiv.appendChild(rightSpan);
    rightSpan.style.transform = "translateY(0px)";
    rightSpan.title = rightSpan.innerText;
    textSpans.push(rightSpan);
    document.getElementById("message-container").appendChild(newDiv); // ☆
    shuffle();
}

function ready() {
    createNewMessage();
    myInterval = Math.random() * 2222;
    setTimeout(ready, myInterval);
}

document.addEventListener("keypress", (e) => {
    // if (e.key == 'm' || e.key == 'a' || e.key == 'y') {
    //     createNewMessage();
    // }
    createNewMessage();
});

function shuffle() {
    for (let i = 0; i < textSpans.length; i++) {
        const y = textSpans[i].getBoundingClientRect().y;

        if (y < -50) {
            document.getElementById("message-container").removeChild(textSpans[i].parentElement);
            textSpans.splice(i, 1);
            i--;
            continue;
        }

        const orig = textSpans[i].title;

        const factor = (window.innerHeight - y) / window.innerHeight / 2 - 0.3;
        let newText = "";

        for (let j = 0; j < orig.length; j++) {
            const char = orig[j];
            if (Math.random() < factor) {
                newText += orig[Math.floor(Math.random() * orig.length)];
            } else {
                newText += char;
            }
        }

        textSpans[i].textContent = newText;
    }
}

ready();
